# Generated by Django 4.0.3 on 2022-03-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carFixInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('mechanic', 'title')},
        ),
    ]
